# Generated by Django 4.0.6 on 2022-10-14 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('remain_in_stock', models.IntegerField()),
                ('amount_ordered', models.IntegerField()),
                ('ordered_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TechProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainroot.product')),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('manuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainroot.manufact')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainroot.provider')),
            ],
            bases=('mainroot.product',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('techproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainroot.techproduct')),
                ('size', models.IntegerField()),
                ('mem_type', models.IntegerField()),
            ],
            bases=('mainroot.techproduct',),
        ),
        migrations.CreateModel(
            name='Proccessor',
            fields=[
                ('techproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainroot.techproduct')),
                ('freq', models.IntegerField()),
                ('socket', models.CharField(max_length=30)),
                ('c_memory', models.IntegerField()),
            ],
            bases=('mainroot.techproduct',),
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('techproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainroot.techproduct')),
                ('freq', models.IntegerField()),
                ('v_memory', models.IntegerField()),
                ('memory_type', models.CharField(max_length=30)),
            ],
            bases=('mainroot.techproduct',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainroot.product')),
                ('gabs', models.CharField(max_length=30)),
                ('manuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainroot.manufact')),
                ('memory_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainroot.memory')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainroot.proccessor')),
                ('videocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainroot.videocard')),
            ],
            bases=('mainroot.product',),
        ),
    ]
