# Generated by Django 4.0.6 on 2022-10-17 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainroot', '0003_remove_computer_title_remove_memory_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_fio', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('users_address', models.CharField(blank=True, max_length=100, null=True)),
                ('full_price', models.IntegerField()),
                ('dest_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainroot.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_products', models.ManyToManyField(to='mainroot.product')),
            ],
        ),
    ]
