# Generated by Django 4.0.6 on 2022-11-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainroot', '0004_transport_users_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proccessor',
            options={'verbose_name': 'Proccessor', 'verbose_name_plural': 'Proccessors'},
        ),
    ]
